name: physiozoo-docs

channels:
  - conda-forge

dependencies:
  - python=3.8
  - sphinx=3.3
  - sphinx-autobuild
  - sphinx_rtd_theme
  - recommonmark
  - pip
  - pip:
    - sphinxcontrib-matlabdomain
